# Generated by Django 3.1.4 on 2020-12-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201231_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FilePathField(path='products/img'),
        ),
    ]
